variables:
  buildNumber: $[ counter('constant', 13000) ] # Start higher than our AppVeyor versions. Every build (pr or branch) will increment.

name: 3.0.$(buildNumber)
  
pr:
  branches:
    include:
    - yojagad/CheckDownload

trigger:
  branches:
    include:
    - yojagad/CheckDownload


jobs:
- job: InitializePipeline
  pool:
    vmImage: 'windows-2019'
  steps:
  - task: AzureKeyVault@1
    inputs:
      # Note: This is actually a Service Connection in DevOps, not an Azure subscription name
      azureSubscription: 'Azure-Functions-Host-CI'
      keyVaultName: 'azure-functions-host-ci'
      secretsFilter: '*'
  - task: PowerShell@2
    displayName: 'Initialize'
    name: Initialize
    inputs:
      filePath: '$(Build.Repository.LocalPath)\build\initialize-pipeline.ps1'
      arguments: '-connectionString ''$(Storage-azurefunctionshostci0)'''

- job: BuildArtifacts
  dependsOn: InitializePipeline
  condition: and(succeeded(), or(ne(variables['Build.Reason'], 'PullRequest'), eq(dependencies.InitializePipeline.outputs['Initialize.BuildArtifacts'], true)))
  variables:
    ${{ if or( eq( variables['Build.Reason'], 'PullRequest' ), and( not( endswith( variables['Build.SourceBranch'], 'release/3.0' ) ), not( endswith( variables['Build.SourceBranch'], 'release/ExtensionsMetadataGenerator/1.1' ) ) ) ) }}:
      suffixTemp: ci
      packSuffixSwitchTemp: --version-suffix ci
      emgSuffixSwitchTemp: --version-suffix ci$(buildNumber)
      artifactSuffix: -ci
    suffix: $[variables.suffixTemp] # this resolves to an empty string if it is missing
    packSuffixSwitch: $[variables.packSuffixSwitchTemp]
    emgSuffixSwitch: $[variables.emgSuffixSwitchTemp]
  pool:
    vmImage: 'windows-2019' 
  steps:
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '3.1.x'
      performMultiLevelLookup: true
  - task: PowerShell@2
    displayName: "Build artifacts"
    inputs:
      filePath: '$(Build.Repository.LocalPath)\build\build-extensions.ps1'
      arguments: '-buildNumber "$(buildNumber)" -suffix "$(suffix)" -commitHash "$(Build.SourceVersion)"'
  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(Build.Repository.LocalPath)\buildoutput'
      Contents: '*.zip'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'
  - task: DotNetCoreCLI@2
    displayName: 'Build host packages'
    inputs:
      command: 'custom'
      custom: 'pack'
      arguments: -o packages -p:BuildNumber=$(buildNumber) -p:CommitHash=$(Build.SourceVersion) -c Release $(packSuffixSwitch)
      projects: |
        **\WebJobs.Script.csproj
        **\WebJobs.Script.WebHost.csproj
        **\WebJobs.Script.Grpc.csproj
  - task: DotNetCoreCLI@2
    displayName: 'Build performance package'
    inputs:
      command: 'custom'
      custom: 'pack'
      arguments: '-o packages\WebJobs.Script.Performance.App'
      projects: |
        **\WebJobs.Script.Performance.App.csproj
  - task: DotNetCoreCLI@2
    displayName: 'Build WebJobs.Script.Abstractions'
    inputs:
      command: 'build'
      arguments: '-c Release'
      projects: |
        **\WebJobs.Script.Abstractions.csproj
  - task: DotNetCoreCLI@2
    displayName: 'Pack WebJobs.Script.Abstractions package'
    inputs:
      command: 'custom'
      custom: 'pack'
      arguments: '--no-build -c Release -o packages\WebJobs.Script.Abstractions'
      projects: |
        **\WebJobs.Script.Abstractions.csproj
  - task: DotNetCoreCLI@2
    displayName: 'Build ExtensionsMetadataGenerator'
    inputs:
      command: 'build'      
      arguments: '-c Release -p:CommitHash=$(Build.SourceVersion)'
      projects: |
        **\ExtensionsMetadataGenerator.csproj
  - task: DotNetCoreCLI@2
    displayName: 'Pack ExtensionsMetadataGenerator package'
    inputs:
      command: 'custom'
      custom: 'pack'
      arguments: '--no-build -c Release -o packages\ExtensionsMetadataGenerator $(emgSuffixSwitch)'
      projects: |
        **\ExtensionsMetadataGenerator.csproj
        steps:
  - publish: $(Build.ArtifactStagingDirectory)\Functions.3.0.$(buildNumber)${{ variables.artifactSuffix }}.zip
    artifact: Functions.3.0.$(buildNumber)${{ variables.artifactSuffix }}
  - publish: $(Build.ArtifactStagingDirectory)\Functions.Private.3.0.$(buildNumber)${{ variables.artifactSuffix }}.win-x32.inproc.zip
    artifact: Functions.Private.3.0.$(buildNumber)${{ variables.artifactSuffix }}.win-x32.inproc
  - publish: $(Build.ArtifactStagingDirectory)\Functions.Symbols.3.0.$(buildNumber)${{ variables.artifactSuffix }}.win-x64.zip
    artifact: Functions.Symbols.3.0.$(buildNumber)${{ variables.artifactSuffix }}.win-x64
  - publish: $(Build.ArtifactStagingDirectory)\Functions.Symbols.3.0.$(buildNumber)${{ variables.artifactSuffix }}.win-x86.zip
    artifact: Functions.Symbols.3.0.$(buildNumber)${{ variables.artifactSuffix }}.win-x86
  - publish: $(Build.Repository.LocalPath)\packages\Microsoft.Azure.WebJobs.Script.3.0.$(buildNumber)${{ variables.artifactSuffix }}.nupkg
    artifact: Microsoft.Azure.WebJobs.Script.3.0.$(buildNumber)${{ variables.artifactSuffix }}
  - publish: $(Build.Repository.LocalPath)\packages\ExtensionsMetadataGenerator
    artifact: ExtensionsMetadataGenerator${{ variables.artifactSuffix }}
  - publish: $(Build.Repository.LocalPath)\packages\WebJobs.Script.Performance.App
    artifact: WebJobs.Script.Performance.App${{ variables.artifactSuffix }}
  - publish: $(Build.Repository.LocalPath)\packages\Microsoft.Azure.WebJobs.Script.Grpc.3.0.$(buildNumber)${{ variables.artifactSuffix }}.nupkg
    artifact: Microsoft.Azure.WebJobs.Script.Grpc.3.0.$(buildNumber)${{ variables.artifactSuffix }}
  - publish: $(Build.Repository.LocalPath)\packages\WebJobs.Script.Abstractions
    artifact: Microsoft.Azure.WebJobs.Script.Abstractions${{ variables.artifactSuffix }}
  - publish: $(Build.Repository.LocalPath)\packages\Microsoft.Azure.WebJobs.Script.WebHost.3.0.$(buildNumber)${{ variables.artifactSuffix }}.nupkg
    artifact: Microsoft.Azure.WebJobs.Script.WebHost.3.0.$(buildNumber)${{ variables.artifactSuffix }}